/*
 * Academic Student License -- for use by students to meet course
 * requirements and perform academic research at degree granting
 * institutions only.  Not for government, commercial, or other
 * organizational use.
 * File: Modell_3dof_smblsh_jacobi.c
 *
 * MATLAB Coder version            : 4.1
 * C/C++ source code generated on  : 19-Mar-2020 12:57:10
 */

/* Include Files */
#include <math.h>
#include <string.h>
#include "rt_nonfinite.h"
#include "ffw_exe.h"
#include "Modell_3dof_smblsh_jacobi.h"

/* Function Definitions */

/*
 * MODELL_3DOF_SMBLSH_JACOBI
 *     JACOBI = MODELL_3DOF_SMBLSH_JACOBI(IN1,IN2,IN3,IN4,IN5,STEP_SIZE_SYM)
 * Arguments    : const double in1[6]
 *                const double in3[2]
 *                const double in5[2]
 *                double step_size_sym
 *                double jacobi[64]
 * Return Type  : void
 */
void Modell_3dof_smblsh_jacobi(const double in1[6], const double in3[2], const
  double in5[2], double step_size_sym, double jacobi[64])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t8;
  double t17_tmp;
  double t17;
  double t22;
  double t23_tmp;
  double t23;
  double t24;
  double t27;
  double t29;
  double t32;
  double t33;
  double t36;
  double t40_tmp;
  double t41;
  double t42;
  double t43;
  double t44;
  double t47_tmp;
  double t53;
  double t100;
  double t56_tmp;
  double t56;
  double t60_tmp;
  double t57_tmp;
  double t59_tmp;
  double t64;
  double t65;
  double t68;
  double t71;
  double t72;
  double t76_tmp;
  double t76;
  double t80_tmp;
  double t80;
  double t87_tmp;
  double t88_tmp;
  double t89_tmp;
  double t89;
  double t94_tmp;
  double b_t94_tmp;
  double c_t94_tmp;
  double t94;
  double t96;
  double t98;

  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     19-Mar-2020 12:56:02 */
  t2 = 1.0 / step_size_sym;
  t3 = in1[0] - in1[1];
  t4 = t3 * t3;
  t5 = tanh(in1[0] * 286.47889756541161 - in1[1] * 286.47889756541161);
  t8 = tanh(t4 * t4 * 6.7355109572983932E+9);
  t17_tmp = t8 * ((t5 * t5 * 286.47889756541161 - 286.47889756541161) *
                  3.1415926535897931 * 0.34833333333333333 + 313.5);
  t17 = t17_tmp * 713.62306429743808;
  t22 = (in1[1] * 313.5 + t5 * 3.1415926535897931 * 0.34833333333333333) - in1[0]
    * 313.5;
  t23_tmp = t3 * t4 * (t8 * t8 - 1.0) * t22;
  t23 = t23_tmp * 1.9226463875825E+13;
  t24 = sin(in1[2]);
  t27 = t24 * t24 * 1.2853778820274581E+58;
  t29 = 1.0 / (t27 + 1.473798198206916E+59);
  t32 = (t17_tmp * 6.0036476737691712E+59 + t23_tmp * 1.61750538761725E+70) +
    9.9060186617191325E+60;
  t33 = cos(in1[1]);
  t4 = in1[4] * in1[4];
  t5 = in1[1] + in1[2];
  t36 = cos(t5);
  t3 = in1[5] * in1[5];
  t40_tmp = t36 * in1[4];
  t41 = cos(in1[2]);
  t42 = t33 * t41 * 0.0388934;
  t43 = sin(in1[1]);
  t44 = sin(t5);
  t47_tmp = t44 * in1[4];
  t5 = t41 * t41 * 1.2853778820274581E+58 - 1.602335986409662E+59;
  t53 = 1.0 / t5;
  t100 = t24 * t33 * 0.0388934 + t41 * t43 * 0.0388934;
  t56_tmp = (t4 * t36 * 0.037834046692607 + t36 * t3 * 0.037834046692607) +
    t40_tmp * in1[5] * 0.075668093385214;
  t56 = t56_tmp + t33 * t4 * 0.305;
  t60_tmp = t24 * t43 * 0.0388934;
  t57_tmp = t42 - t60_tmp;
  t59_tmp = (t4 * t44 * 0.037834046692607 + t3 * t44 * 0.037834046692607) +
    t47_tmp * in1[5] * 0.075668093385214;
  t3 = t59_tmp + t4 * t43 * 0.305;
  t64 = t100 + t43 * 0.31354;
  t65 = t33 * 0.31354;
  t4 = t41 * 1.5398388496127559E+36 + 8.5316964853194154E+35;
  t68 = 1.0 / (t5 * t5);
  t71 = (in1[5] * 0.048 + t100 * t56) - t57_tmp * t3;
  t72 = t57_tmp + t65;
  t76_tmp = t47_tmp * 0.075668093385214 + t44 * in1[5] * 0.075668093385214;
  t76 = t76_tmp + t43 * in1[4] * 0.61;
  t80_tmp = t40_tmp * 0.075668093385214 + t36 * in1[5] * 0.075668093385214;
  t80 = t80_tmp + t33 * in1[4] * 0.61;
  t87_tmp = t56 * t57_tmp;
  t88_tmp = t100 * t3;
  t89_tmp = t87_tmp + t88_tmp;
  t89 = (t89_tmp - t100 * t59_tmp) - t57_tmp * t56_tmp;
  t94_tmp = t8 * t22;
  b_t94_tmp = t56 * t64;
  c_t94_tmp = t3 * t72;
  t94 = ((((in1[1] * 16.5 + in1[4] * 0.16171875) + t94_tmp) + b_t94_tmp) - in1[0]
         * 16.5) - c_t94_tmp;
  t96 = t41 * 2.4059982025199309E+41 + 2.77327796509712E+42;
  t98 = t57_tmp * t76 - t100 * t80;
  t100 = (t100 * t80_tmp - t57_tmp * t76_tmp) + 0.048;
  t22 = in5[1] * t36;
  jacobi[0] = t2;
  jacobi[1] = 0.0;
  jacobi[2] = 0.0;
  jacobi[3] = (t17 + t23) + 11774.78056090773;
  jacobi[4] = -t29 * t32;
  t8 = t53 * t4;
  t56 = t8 * ((t17_tmp + t23_tmp * 2.6942043829193569E+10) + 16.5);
  jacobi[5] = t56 * -7.0368744177664E+23;
  jacobi[6] = 0.0;
  jacobi[7] = 0.0;
  jacobi[8] = 0.0;
  jacobi[9] = t2;
  jacobi[10] = 0.0;
  jacobi[11] = (-t17 - t23) - 11774.78056090773;
  jacobi[12] = t29 * t32;
  jacobi[13] = t56 * 7.0368744177664E+23;
  jacobi[14] = -in5[0] * t43 - in5[1] * t44;
  jacobi[15] = t22 + in5[0] * t33;
  jacobi[16] = 0.0;
  jacobi[17] = 0.0;
  jacobi[18] = t2;
  jacobi[19] = 0.0;
  t56 = t24 * t53;
  t5 = t24 * t41;
  t40_tmp = t5 * t4 * t68;
  t3 = t59_tmp * t64;
  t4 = t56 * t71;
  t47_tmp = t56 * in3[1];
  jacobi[20] = (((((t29 * (((t88_tmp * 6.0036476737691712E+59 + t87_tmp *
    6.0036476737691712E+59) - t3 * 6.0036476737691712E+59) - t56_tmp * ((t42 +
    t65) - t60_tmp) * 6.0036476737691712E+59) - t4 * 1.0835652608322849E+60) +
                   t8 * t89 * 7.0368744177664E+23) + t47_tmp *
                  1.0835652608322849E+60) - t24 / ((t27 + 1.473798198206916E+59)
    * (t27 + 1.473798198206916E+59)) * t41 * (((((in1[0] *
    -9.9060186617191325E+60 + in1[1] * 9.9060186617191325E+60) + in1[4] *
    9.7090239724235816E+58) + t94_tmp * 6.0036476737691712E+59) + b_t94_tmp *
    6.0036476737691712E+59) - c_t94_tmp * 6.0036476737691712E+59) *
                 2.5707557640549162E+58) + t40_tmp * t71 *
                1.8090085470403549E+82) - t40_tmp * in3[1] *
    1.8090085470403549E+82;
  t5 *= t68;
  jacobi[21] = ((((((t8 * ((t89_tmp - t3) - t56_tmp * t72) * 7.0368744177664E+23
                     + t4 * 2.1671305216645692E+60) - t56 * t94 *
                    1.0835652608322849E+60) - t53 * t89 * t96 *
                   9.007199254740992E+18) - t47_tmp * 2.1671305216645692E+60) +
                 t40_tmp * t94 * 1.8090085470403549E+82) - t5 * t71 * t96 *
                2.3155309402116549E+77) + t5 * t96 * in3[1] *
    2.3155309402116549E+77;
  jacobi[22] = -in5[1] * t44;
  jacobi[23] = t22;
  jacobi[24] = -1.0;
  jacobi[25] = 0.0;
  jacobi[26] = 0.0;
  jacobi[27] = t2 + 99.907229001641326;
  jacobi[28] = 0.0;
  jacobi[29] = 0.0;
  jacobi[30] = 0.0;
  jacobi[31] = 0.0;
  jacobi[32] = 0.0;
  jacobi[33] = -1.0;
  jacobi[34] = 0.0;
  jacobi[35] = 0.0;
  t56 = t64 * t80;
  t40_tmp = t72 * t76;
  jacobi[36] = (t2 + t29 * ((t56 * 6.0036476737691712E+59 - t40_tmp *
    6.0036476737691712E+59) + 9.7090239724235816E+58)) - t8 * t98 *
    7.0368744177664E+23;
  t3 = t53 * t96;
  jacobi[37] = t8 * ((t56 - t40_tmp) + 0.16171875) * 7.0368744177664E+23 + t3 *
    t98 * 9.007199254740992E+18;
  jacobi[38] = 0.0;
  jacobi[39] = 0.0;
  jacobi[40] = 0.0;
  jacobi[41] = 0.0;
  jacobi[42] = -1.0;
  jacobi[43] = 0.0;
  t56 = t64 * t80_tmp;
  t40_tmp = t72 * t76_tmp;
  jacobi[44] = t29 * (t56 * 6.0036476737691712E+59 - t40_tmp *
                      6.0036476737691712E+59) + t8 * t100 * 7.0368744177664E+23;
  jacobi[45] = (t2 + t8 * (t56 - t40_tmp) * 7.0368744177664E+23) - t3 * t100 *
    9.007199254740992E+18;
  jacobi[46] = 0.0;
  jacobi[47] = 0.0;
  jacobi[48] = 0.0;
  jacobi[49] = 0.0;
  jacobi[50] = 0.0;
  jacobi[51] = -713.62306429743808;
  memset(&jacobi[52], 0, sizeof(double) << 3);
  jacobi[60] = t8 * -7.0368744177664E+23;
  jacobi[61] = t3 * 9.007199254740992E+18;
  jacobi[62] = 0.0;
  jacobi[63] = 0.0;
}

/*
 * File trailer for Modell_3dof_smblsh_jacobi.c
 *
 * [EOF]
 */
