/*
 * Academic Student License -- for use by students to meet course
 * requirements and perform academic research at degree granting
 * institutions only.  Not for government, commercial, or other
 * organizational use.
 * File: MKS_4dof_ffw.c
 *
 * MATLAB Coder version            : 4.1
 * C/C++ source code generated on  : 24-Feb-2020 21:35:30
 */

/* Include Files */
#include <math.h>
#include "rt_nonfinite.h"
#include "ffw_exe.h"
#include "MKS_4dof_ffw.h"

/* Function Definitions */

/*
 * MKS_4DOF_FFW
 *     FFW_SYM = MKS_4DOF_FFW(IN1,IN2,IN3,IN4,IN5)
 * Arguments    : const double in1[10]
 *                const double in2[8]
 *                const double in3[2]
 *                const double in4_data[]
 *                const double in5[14]
 *                double ffw_sym[10]
 * Return Type  : void
 */
void MKS_4dof_ffw(const double in1[10], const double in2[8], const double in3[2],
                  const double in4_data[], const double in5[14], double ffw_sym
                  [10])
{
  double t2;
  double t7;
  double t8;
  double t9_tmp;
  double t9;
  double t10;
  double t13;
  double t14_tmp;
  double t14;
  double t18;
  double t19;
  double t20;
  double t21;
  double t71;
  double t23;
  double t24;
  double t31;
  double t45;
  double t53_tmp;
  double t55_tmp_tmp;
  double t55_tmp;
  double t55;
  double t62_tmp;
  double t62;
  double t63_tmp;
  double t63;
  double t65_tmp;
  double t67_tmp;

  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     24-Feb-2020 21:21:20 */
  t2 = 1.0 / in5[4];
  t7 = in2[2] + in2[3];
  t8 = cos(t7);
  t9_tmp = in5[9] * t8;
  t9 = t9_tmp * in2[7] / 2.0;
  t10 = sin(t7);
  t13 = in5[8] * sin(in2[2]);
  t14_tmp = in5[9] * t10;
  t14 = t14_tmp / 2.0 + t13;
  t7 = t14_tmp * in2[7] / 2.0;
  t18 = in5[8] * cos(in2[2]);
  t19 = t9_tmp / 2.0 + t18;
  t20 = in5[8] * in5[8];
  t21 = in5[9] * in5[9];
  t71 = sin(in2[3]);
  t23 = in5[7] * 4.0;
  t24 = in5[3] * t21;
  t31 = (t9 + t9_tmp * in2[6] / 2.0) * in2[7] + (t9 + t19 * in2[6]) * in2[6];
  t9 = (t7 + t14_tmp * in2[6] / 2.0) * in2[7] + (t7 + t14 * in2[6]) * in2[6];
  t45 = cos(in2[3]);
  t53_tmp = t20 * t21 * (in5[3] * in5[3]);
  t55_tmp_tmp = (((((in5[6] * in5[7] * 16.0 + in5[1] * in5[7] * t20 * 16.0) +
                    in5[2] * in5[7] * t20 * 4.0) + in5[3] * in5[6] * t21 * 4.0)
                  + in5[3] * in5[7] * t20 * 16.0) + in5[1] * in5[3] * t20 * t21 *
                 4.0) + in5[2] * in5[3] * t20 * t21;
  t55_tmp = t55_tmp_tmp + t53_tmp * (t71 * t71) * 4.0;
  t55 = 1.0 / t55_tmp;
  t7 = t23 + t24;
  t62_tmp = in5[10] * (in2[0] - in2[2]) + in5[11] * (in2[4] - in2[6]);
  t62 = (t62_tmp + in5[3] * t19 * t9) - in5[3] * t14 * t31;
  t63_tmp = t55 * t7;
  t63 = t63_tmp * t62 * 4.0;
  t65_tmp = in5[3] * in5[8] * in5[9] * t45;
  t19 = t7 + t65_tmp * 2.0;
  t7 = in5[3] * in5[9];
  t67_tmp = in5[12] * (in2[1] - in2[3]) + in5[13] * (in2[5] - in2[7]);
  t14 = (t67_tmp + t7 * t8 * t9 / 2.0) - t7 * t10 * t31 / 2.0;
  t71 = 1.0 / ((t55_tmp_tmp + t53_tmp * 4.0) - t53_tmp * (t45 * t45) * 4.0);
  ffw_sym[0] = in1[0] - in2[4];
  ffw_sym[1] = in1[1] - in2[5];
  ffw_sym[2] = in1[2] - in2[6];
  ffw_sym[3] = in1[3] - in2[7];
  ffw_sym[4] = (in1[4] + t2 * t62_tmp) - t2 * in3[0];
  t7 = t55 * (1.0 / in5[5]) * ((t55_tmp + in5[5] * in5[7] * 16.0) + in5[3] *
    in5[5] * t21 * 4.0);
  t9 = t19 * t14 * t71 * 4.0;
  ffw_sym[5] = (((in1[5] + t63) - t9) + t7 * t67_tmp) - t7 * in3[1];
  ffw_sym[6] = (((in1[6] - t63) - t63_tmp * t67_tmp * 4.0) + t9) + t63_tmp *
    in3[1] * 4.0;
  t7 = t19 * t71;
  ffw_sym[7] = (((in1[7] - t14 * t71 * ((((((in5[6] * 4.0 + t23) + t24) + in5[1]
    * t20 * 4.0) + in5[2] * t20) + in5[3] * t20 * 4.0) + t65_tmp * 4.0) * 4.0) +
                 t62 * t19 * t71 * 4.0) + t7 * t67_tmp * 4.0) - t7 * in3[1] *
    4.0;
  ffw_sym[8] = (-in4_data[0] + t18) + t9_tmp;
  ffw_sym[9] = (-in4_data[1] + t13) + t14_tmp;
}

/*
 * File trailer for MKS_4dof_ffw.c
 *
 * [EOF]
 */
