/*
 * Academic Student License -- for use by students to meet course
 * requirements and perform academic research at degree granting
 * institutions only.  Not for government, commercial, or other
 * organizational use.
 * File: MKS_4dof_jacobi.c
 *
 * MATLAB Coder version            : 4.1
 * C/C++ source code generated on  : 24-Feb-2020 21:35:30
 */

/* Include Files */
#include <math.h>
#include <string.h>
#include "rt_nonfinite.h"
#include "ffw_exe.h"
#include "MKS_4dof_jacobi.h"

/* Function Definitions */

/*
 * MKS_4DOF_JACOBI
 *     JACOBI = MKS_4DOF_JACOBI(IN1,IN2,IN3,IN4,IN5,STEP_SIZE_SYM)
 * Arguments    : const double in1[8]
 *                const double in3[2]
 *                const double in5[14]
 *                double jacobi[100]
 * Return Type  : void
 */
void MKS_4dof_jacobi(const double in1[8], const double in3[2], const double in5
                     [14], double jacobi[100])
{
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;
  double t8;
  double t16;
  double t17;
  double t105;
  double t88;
  double t81;
  double t22_tmp;
  double t23;
  double t24_tmp;
  double t25;
  double t107;
  double t27_tmp;
  double t27;
  double t28;
  double t29;
  double t31_tmp;
  double t109;
  double t31;
  double t110;
  double t32;
  double t33;
  double t34_tmp;
  double t113;
  double t34;
  double t35;
  double t37_tmp;
  double t38;
  double t41;
  double t42;
  double t45;
  double t46;
  double t48;
  double t51;
  double t52;
  double t54;
  double t59_tmp;
  double t59;
  double t64;
  double t65;
  double t68;
  double t69_tmp;
  double t69;
  double t76_tmp;
  double t76;
  double t78;
  double t89_tmp;
  double t89;
  double t90;
  double t91_tmp;
  double t91;
  double t93_tmp_tmp;
  double t93_tmp;
  double t93;
  double t99;
  double t100;

  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     24-Feb-2020 20:25:23 */
  t3 = 1.0 / in5[4];
  t4 = in5[10] * t3;
  t5 = in5[11] * t3;
  t6 = in5[8] * in5[8];
  t7 = in5[9] * in5[9];
  t8 = sin(in1[3]);
  t16 = in5[3] * in5[3];
  t17 = cos(in1[3]);
  t105 = t6 * t7;
  t88 = t105 * t16;
  t81 = (((((in5[6] * in5[7] * 16.0 + in5[1] * in5[7] * t6 * 16.0) + in5[2] *
            in5[7] * t6 * 4.0) + in5[3] * in5[6] * t7 * 4.0) + in5[3] * in5[7] *
          t6 * 16.0) + in5[1] * in5[3] * t6 * t7 * 4.0) + in5[2] * in5[3] * t6 *
    t7;
  t22_tmp = t81 + t88 * (t8 * t8) * 4.0;
  t23 = 1.0 / t22_tmp;
  t24_tmp = in5[7] * 4.0 + in5[3] * t7;
  t25 = in5[10] * t23 * t24_tmp * 4.0;
  t107 = in5[3] * in5[8] * in5[9];
  t27_tmp = t107 * t17;
  t27 = t24_tmp + t27_tmp * 2.0;
  t28 = in1[2] + in1[3];
  t29 = sin(t28);
  t31_tmp = in5[9] * t29;
  t109 = t31_tmp * in1[7];
  t31 = t109 / 2.0;
  t110 = t31_tmp * in1[6];
  t32 = t110 / 2.0 + t31;
  t33 = cos(t28);
  t34_tmp = in5[9] * t33;
  t113 = t34_tmp * in1[7];
  t34 = t113 / 2.0;
  t35 = t32 * in1[7];
  t37_tmp = t34_tmp * in1[6];
  t28 = t34 + t37_tmp / 2.0;
  t38 = t28 * in1[7];
  t41 = (t81 + t88 * 4.0) - t88 * (t17 * t17) * 4.0;
  t42 = 1.0 / t41;
  t45 = in5[8] * cos(in1[2]);
  t46 = t34_tmp / 2.0 + t45;
  t48 = t38 + t28 * in1[6];
  t51 = in5[8] * sin(in1[2]);
  t52 = t31_tmp / 2.0 + t51;
  t54 = t35 + t32 * in1[6];
  t81 = t46 * in1[6];
  t34 = t38 + (t34 + t81) * in1[6];
  t28 = in5[3] * in5[9];
  t59_tmp = t28 * t33;
  t59 = t59_tmp * t34 / 2.0;
  t88 = t52 * in1[6];
  t32 = t35 + (t31 + t88) * in1[6];
  t31 = t28 * t29;
  t64 = t31 * t32 / 2.0;
  t65 = 1.0 / in5[5];
  t68 = (t22_tmp + in5[5] * in5[7] * 16.0) + in5[3] * in5[5] * t7 * 4.0;
  t69_tmp = in5[12] * t23;
  t69 = t69_tmp * t65 * t68;
  t76_tmp = in5[12] * (in1[1] - in1[3]) + in5[13] * (in1[5] - in1[7]);
  t76 = (t76_tmp + t59_tmp * t32 / 2.0) - t31 * t34 / 2.0;
  t78 = 1.0 / (t22_tmp * t22_tmp);
  t81 = t81 * 2.0 + t113;
  t28 = t88 * 2.0 + t109;
  t33 = t113 + t37_tmp;
  t88 = t109 + t110;
  t89_tmp = in5[13] * t23;
  t89 = t89_tmp * t65 * t68;
  t90 = (((in5[12] + t59) + t64) - t31 * t54 / 2.0) - t59_tmp * t48 / 2.0;
  t91_tmp = t27 * t42;
  t91 = t91_tmp * t90 * 4.0;
  t93_tmp_tmp = t107 * t8 * t42;
  t93_tmp = t93_tmp_tmp * t76;
  t93 = t93_tmp * 8.0;
  t35 = in5[3] * t52;
  t38 = in5[3] * t46;
  t99 = ((in5[10] * (in1[0] - in1[2]) + in5[11] * (in1[4] - in1[6])) + t38 * t32)
    - t35 * t34;
  t100 = 1.0 / (t41 * t41);
  t46 = t105 * t8 * t16 * t17;
  t41 = t46 * t27;
  t8 = t41 * t76 * t100 * 32.0;
  t16 = in5[11] * t23 * t24_tmp * 4.0;
  t17 = t31 * t81 / 2.0 - t59_tmp * t28 / 2.0;
  t105 = t91_tmp * t17 * 4.0;
  t107 = (in5[11] + t35 * t81) - t38 * t28;
  t109 = (in5[13] + t31 * t33 / 2.0) - t59_tmp * t88 / 2.0;
  t110 = t91_tmp * t109 * 4.0;
  t52 = t23 * t24_tmp;
  t22_tmp = t38 * t88 - t35 * t33;
  t113 = t52 * t22_tmp * 4.0;
  t37_tmp = in5[12] * t27 * t42 * 4.0;
  t28 = in5[10] * t27 * t42 * 4.0;
  t7 = ((t59 + t64) - t38 * t48) - t35 * t54;
  t35 = ((((t24_tmp + in5[6] * 4.0) + in5[1] * t6 * 4.0) + in5[2] * t6) + in5[3]
         * t6 * 4.0) + t27_tmp * 4.0;
  t31 = in5[13] * t27 * t42 * 4.0;
  jacobi[0] = 100.0;
  jacobi[1] = 0.0;
  jacobi[2] = 0.0;
  jacobi[3] = 0.0;
  jacobi[4] = t4;
  jacobi[5] = t25;
  jacobi[6] = -t25;
  jacobi[7] = t28;
  jacobi[8] = 0.0;
  jacobi[9] = 0.0;
  jacobi[10] = 0.0;
  jacobi[11] = 100.0;
  jacobi[12] = 0.0;
  jacobi[13] = 0.0;
  jacobi[14] = 0.0;
  jacobi[15] = t69 - t37_tmp;
  t33 = t69_tmp * t24_tmp * 4.0;
  jacobi[16] = t37_tmp - t33;
  jacobi[17] = t37_tmp - in5[12] * t42 * t35 * 4.0;
  jacobi[18] = 0.0;
  jacobi[19] = 0.0;
  jacobi[20] = 0.0;
  jacobi[21] = 0.0;
  jacobi[22] = 100.0;
  jacobi[23] = 0.0;
  jacobi[24] = -t4;
  jacobi[25] = -t25;
  jacobi[26] = t25;
  jacobi[27] = -t28;
  jacobi[28] = -t51 - t31_tmp;
  jacobi[29] = t45 + t34_tmp;
  jacobi[30] = 0.0;
  jacobi[31] = 0.0;
  jacobi[32] = 0.0;
  jacobi[33] = 100.0;
  jacobi[34] = 0.0;
  t28 = t46 * t23 * t65;
  t88 = t46 * t65 * t68;
  t81 = t52 * t7 * 4.0;
  t32 = t46 * t24_tmp;
  t34 = t32 * t78;
  t38 = t34 * t99 * 32.0;
  jacobi[35] = ((((((((-t69 + t91) + t93) + t8) - t81) - t28 * in3[1] * 8.0) +
                  t28 * t76_tmp * 8.0) - t38) - t88 * t76_tmp * t78 * 8.0) + t88
    * t78 * in3[1] * 8.0;
  jacobi[36] = ((((((-t91 - t93) - t8) + t33) + t81) - t34 * in3[1] * 32.0) +
                t32 * t76_tmp * t78 * 32.0) + t38;
  jacobi[37] = (((((((((-t37_tmp - t91_tmp * t7 * 4.0) + t42 * t90 * t35 * 4.0)
                      + t93_tmp * 16.0) - t93_tmp_tmp * t76_tmp * 8.0) -
                    t93_tmp_tmp * t99 * 8.0) + t93_tmp_tmp * in3[1] * 8.0) + t41
                  * t100 * in3[1] * 32.0) - t41 * t76_tmp * t100 * 32.0) - t41 *
                t99 * t100 * 32.0) + t46 * t76 * t100 * t35 * 32.0;
  jacobi[38] = -in5[9] * t29;
  jacobi[39] = t34_tmp;
  jacobi[40] = -1.0;
  jacobi[41] = 0.0;
  jacobi[42] = 0.0;
  jacobi[43] = 0.0;
  jacobi[44] = 100.0 + t5;
  jacobi[45] = t16;
  jacobi[46] = -t16;
  jacobi[47] = in5[11] * t27 * t42 * 4.0;
  jacobi[48] = 0.0;
  jacobi[49] = 0.0;
  jacobi[50] = 0.0;
  jacobi[51] = -1.0;
  jacobi[52] = 0.0;
  jacobi[53] = 0.0;
  jacobi[54] = 0.0;
  jacobi[55] = (100.0 + t89) - t31;
  t33 = t89_tmp * t24_tmp * 4.0;
  jacobi[56] = t31 - t33;
  jacobi[57] = t31 - in5[13] * t42 * t35 * 4.0;
  jacobi[58] = 0.0;
  jacobi[59] = 0.0;
  jacobi[60] = 0.0;
  jacobi[61] = 0.0;
  jacobi[62] = -1.0;
  jacobi[63] = 0.0;
  jacobi[64] = -t5;
  t28 = t52 * t107 * 4.0;
  jacobi[65] = t105 - t28;
  jacobi[66] = (100.0 - t105) + t28;
  jacobi[67] = t91_tmp * t107 * -4.0 + t42 * t17 * t35 * 4.0;
  jacobi[68] = 0.0;
  jacobi[69] = 0.0;
  jacobi[70] = 0.0;
  jacobi[71] = 0.0;
  jacobi[72] = 0.0;
  jacobi[73] = -1.0;
  jacobi[74] = 0.0;
  jacobi[75] = (-t89 + t110) + t113;
  jacobi[76] = (-t110 - t113) + t33;
  jacobi[77] = ((100.0 - t31) + t42 * t109 * t35 * 4.0) + t91_tmp * t22_tmp *
    4.0;
  jacobi[78] = 0.0;
  jacobi[79] = 0.0;
  jacobi[80] = 0.0;
  jacobi[81] = 0.0;
  jacobi[82] = 0.0;
  jacobi[83] = 0.0;
  jacobi[84] = -t3;
  memset(&jacobi[85], 0, 10U * sizeof(double));
  jacobi[95] = -t23 * t65 * t68;
  jacobi[96] = t52 * 4.0;
  jacobi[97] = t91_tmp * -4.0;
  jacobi[98] = 0.0;
  jacobi[99] = 0.0;
}

/*
 * File trailer for MKS_4dof_jacobi.c
 *
 * [EOF]
 */
